version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "cron"
      cronjob: "6 4 2 */3 *"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: "cron"
      cronjob: "6 4 2 */3 *"
