name: CLI E2E tests
on:
  pull_request:

permissions:
  contents: read

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            sum.golang.org:443
            ppa.launchpadcontent.net:443
            packages.microsoft.com:443
            azure.archive.ubuntu.com:80
            motd.ubuntu.com:443
            esm.ubuntu.com:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup OS
#        uses: awalsh128/cache-apt-pkgs-action@a6c3917cc929dd0345bfb2d3feaf9101823370ad # v1.4.2
#        with:
#          packages: libseccomp-dev
        run: sudo apt-get update && sudo apt-get install -y libseccomp-dev

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: make

      - name: Build executable
        run: make sortof-linux_amd64

      - name: Run E2E tests
        run: make CLI=sortof-linux_amd64 e2e

  windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: make

      - name: Build executable
        run: make sortof-windows_amd64.exe

      - name: Run E2E tests
        run: make CLI=sortof-windows_amd64.exe e2e

  openbsd:
    name: OpenBSD
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            proxy.golang.org:443
            sum.golang.org:443
            pool.ntp.org:443
            cdn.openbsd.org:443
            www.google.com:443
            raw.githubusercontent.com:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            time.cloudflare.com:443
            ppa.launchpadcontent.net:443
            packages.microsoft.com:443
            azure.archive.ubuntu.com:80
            motd.ubuntu.com:443
            esm.ubuntu.com:443
            pypi.org:443
            files.pythonhosted.org:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: make

      - name: Build executable for OpenBSD amd64
        run: make sortof-openbsd_amd64

      - name: Run E2E tests inside VM
        uses: vmactions/openbsd-vm@0d65352eee1508bab7cb12d130536d3a556be487 # v1.1.8
        with:
          run: |
            make CLI=sortof-openbsd_amd64 e2e
