name: CLI E2E tests
on:
  pull_request:

permissions:
  contents: read

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            ppa.launchpadcontent.net:443
            packages.microsoft.com:443
            azure.archive.ubuntu.com:80
            motd.ubuntu.com:443
            esm.ubuntu.com:443

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup seccomp
        uses: awalsh128/cache-apt-pkgs-action@44c33b32f808cdddd5ac0366d70595ed63661ed8 # v1.3.1
        with:
          packages: libseccomp-dev

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: make

      - name: Build executable
        run: make sortof-linux_amd64

      - name: Run E2E tests
        run: make CLI=sortof-linux_amd64 e2e

  windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: make

      - name: Build executable
        run: make sortof-windows_amd64.exe

      - name: Run E2E tests
        run: make CLI=sortof-windows_amd64.exe e2e

  openbsd:
    name: OpenBSD
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            proxy.golang.org:443
            pool.ntp.org:443
            cdn.openbsd.org:443
            www.google.com:443
            raw.githubusercontent.com:443
            objects.githubusercontent.com:443
            time.cloudflare.com:443
            ppa.launchpadcontent.net:443
            packages.microsoft.com:443
            azure.archive.ubuntu.com:80
            motd.ubuntu.com:443
            esm.ubuntu.com:443
            pypi.org:443
            files.pythonhosted.org:443

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: make

      - name: Build executable for OpenBSD amd64
        run: make sortof-openbsd_amd64

      - name: Run E2E tests inside VM
        uses: vmactions/openbsd-vm@7bfcccb9cf1fa7a1f2f1b7e7718e0d68e70643ac # v1.0.6
        with:
          run: |
            make CLI=sortof-openbsd_amd64 e2e
